<add>migration実装
fjsho/codegym-laravel-tutorial-for-team pull request #1
Opened 2021-12-18 06:08 UTC by giyana

2021-12-18 06:10 UTC, giyana commented
データベース定義書
chrome-extension://gbkeegbaiigmenfmjfclcdgdpimamgkj/views/app.html

2021-12-20 03:05 UTC, masayoshixxx requested changes
更新ありがとうございます！
自分も講師レビューで受けた指摘の受け売りなのですが、
マイグレーションファイルは既存のものを書き換えるではなく
（既存のファイルは書き換えてはいけないとかいさんに指摘されました）
make:migrationで更新したファイルのup()とdown()に追記していくみたいです！
内容はこの記述でいいんじゃないかと自分は思っています！

2021-12-20 03:15 UTC, masayoshixxx approved these changes

2021-12-20 12:33 UTC, giyana commented
追加するテーブル、カラムを、新しく作ったマイグレーションファイルのup()とdown()に追記しました。

2021-12-21 10:57 UTC, masayoshixxx reviewed
確認させていただきました。
自分の調べた限りではこれでいいんじゃないかと思います！

2021-12-24 01:36 UTC, DaisukeKikukawa commented
すみません確認遅くなりました🙏
自分もこれで良いと思います！

2021-12-25 00:33 UTC, merged