Feature/add items
fjsho/codegym-laravel-tutorial-for-team pull request #4
Opened 2022-01-14 10:35 UTC by masayoshixxx

優先度・実施時間の入力欄作成（課題作成・編集）

・「課題の作成」「課題の編集」へ以下の項目を追加する
　　優先度
　　実施時間（=タスクに費やした時間）
・仕様
 　　優先度はリストから選択できるようにする
 　　実施時間は以下の条件で入力できるようにする
　　　　単位：時間（h）
　　　　型：数値（小数点第二位までOK）
　　　　最小値：0
　　　　最大値：999.99
　　　　エラーメッセージ：「実施時間は、1000時間未満にしてください。」
　　　　マイナス値は不可
　　　　入力は任意

2022-01-15 03:06 UTC, fjsho requested changes
佐藤さん実装お疲れ様です！
インデントや文字間のスペースがきれいに整っていてとても見やすかったです！
動作確認で不安定な部分があったのでコードと合わせてご確認をお願いします。

## 動作について
- 優先度
  - 「課題の作成」
    - 大中小の登録はOKでした！
    - nullでの登録はエラーが出ました（新規・更新画面共に）
  - 「課題の編集」
    - 登録済みの優先度（大中小）が表示されませんでした（DBには登録されていました）
  - 再現方法
    - 優先度以外の設定を以下の値にして、優先度を大,中,小,nullにして登録・更新する
      - 種別：タスク
      - 課題名：（任意の有効値）
      - 状態：処理中
      - 担当者、カテゴリー、期限日：null
      - 実施時間：500
- 実施時間
  - 「課題の作成」
    - 有効値（0~999.99）はバリデーションをパスしました！
      - ただ、DBへの登録ができませんでした（"NULL"で登録されてしまう）
    - null値は仕様では許容されていますが、バリデーションに引っかかりました
    - マイナス値や1000以上の値はバリデーションを通過しました
    - 文字列や改行はバリデーションでチェックできていました
    - 小数点第三位以下をもつ数値はバリデーションをパスしました。
    - 表にまとめたもの（細かくて少し見づらいかもしれません...）
    - <img width="1084" alt="スクリーンショット 2022-01-15 11 57 49" src="https://user-images.githubusercontent.com/81564274/149606437-bdcae705-93ae-4152-b6ab-169cfc6d280a.png">
    - 課題の編集については、未確認です。
    - 再現方法
      - 実施時間以外の設定を以下の値にし、実施時間に上記のテストデータを入力して登録する
        - 種別：タスク
        - 課題名：（任意の有効値）
        - 状態：処理中
        - 担当者、カテゴリー、期限日：null
        - 優先度：中

2022-01-15 03:06 UTC, fjsho commented on application/resources/views/tasks/create.blade.php
> +                        <x-textarea id="actual_time" class="block mt-1 w-full {{ $errors->has('actual_time') ? 'border-red-600' :'' }}" type="text" name="actual_time" :value="old('actual_time')" plac
1. 実施時間の入力欄をimputではなくtextareaにしているのはなぜですか？
　（imputだと不具合が起きる感じでしょうか？コンポーネントのtextareaも修正してあったので意図があるんだと思いますが確認です。的外れだったらすみません🙇‍♂️）
2. placeholder属性の「１」が全角になっています。ここは半角でいいのかなと思います。

2022-01-15 03:06 UTC, fjsho commented on application/resources/views/tasks/edit.blade.php
> +                        <x-textarea id="actual_time" class="block mt-1 w-full {{ $errors->has('actual_time') ? 'border-red-600' :'' }}" type="text" name="actual_time" :value="old('actual_time')" plac
前段create.blade.phpへの質問と同様です。
1. textareaの理由
2. placeholder属性の「１」→「1」

※1については意図があれば修正不要です。

2022-01-15 03:06 UTC, fjsho commented on application/resources/views/tasks/create.blade.php
> +    </form>
ここはdivがいっこ増えてformがずれている感じでした。
手違いだと思うので元の状態してもらえればと思います！

2022-01-21 12:43 UTC, masayoshixxx commented on application/resources/views/tasks/create.blade.php
> +                        <x-textarea id="actual_time" class="block mt-1 w-full {{ $errors->has('actual_time') ? 'border-red-600' :'' }}" type="text" name="actual_time" :value="old('actual_time')" plac
textareaは半角文字（数字）を書き入れる仕様だったので、とりあえず前回の「総合課題１」の詳細記入欄を引用しようと思いbladeからごっそり引っ張ってきたためです！藤原さんのとおりinputの方が適切だと思いましたのでここは修正しました！

2022-01-22 00:39 UTC, fjsho commented
お疲れ様です。
レビュー箇所について修正ありがとうございました！
バリデーションは全て仕様通りの動作になっていました😊
優先度：nullでエラーが出たのでそこだけご対応よろしくお願いします！

### 動作確認チェックリスト
- 優先度
  - 「課題の作成」
    - [x] 大中小の登録
    - [ ] nullでの登録
      - nullが許可されていないようでした
<img width="944" alt="スクリーンショット 2022-01-22 10 19 51" src="https://user-images.githubusercontent.com/81564274/150619064-2093a7c7-91b8-45f0-8dd0-ebf683f83fc2.png">

  - 「課題の編集」
    - [x] 登録済みの優先度（大中小）が表示される
    - [x] 大中小の登録
    - [ ] nullでの登録
      - nullが許可されていないようでした
<img width="944" alt="スクリーンショット 2022-01-22 10 21 27" src="https://user-images.githubusercontent.com/81564274/150619079-41bf5165-6229-4528-ad6a-f4633459070f.png">

- 実施時間
  - 「課題の作成」
    - [x] DBへの登録
    - [x] バリデーション
![スクリーンショット 2022-01-22 10 00 20](https://user-images.githubusercontent.com/81564274/150618191-62d4886d-e812-419c-a6d4-e04dfa76b0de.png)

  - 「課題の編集」
    - [x] DBへの登録
    - [x] バリデーション
![スクリーンショット 2022-01-22 10 00 56](https://user-images.githubusercontent.com/81564274/150618218-5475b5b2-2e21-4c40-92c5-801f1b1384ed.png)

2022-01-22 01:07 UTC, TomoakiTANAKA requested changes

2022-01-22 01:07 UTC, TomoakiTANAKA commented on application/resources/lang/ja/validation.php
> +    'regex'                => '実施時間は0〜999.99までの半角数字（小数点以下２桁まで）にしてください。',
[info]

`regex`は正規表現という意味ですね
エラーメッセージは、きちんと指定した範囲内に収めてね、という内容ですので、`regex`は不適切かと思います。
ユーザー（利用者）に見える（近い）レイヤーでは、実装内容から切り話した単語を使うことが多いです。

2022-01-22 01:07 UTC, TomoakiTANAKA commented on application/tests/Feature/TaskEditTest.php
> +            'task_priority_id' => 'ほげ',
[info]

テストコードは、初期生成のものを利用しており、実装していないのかもですが「ほげ」というのはやめておくのがベターです。

理由
- idと書いてあり数字かな？と思うところに「ほげ」と書いてあり、読みてからするとなぜ？と余計な疑問をもたせてしまう
- テストコードは、対象となるメソッドやモデルのサンプル（使い方）を説明するものなので、適切な値が良い
- 「ほげ」とかを残すと、この人大丈夫かな？と思われるときがある

2022-01-22 01:07 UTC, TomoakiTANAKA commented on application/app/Http/Controllers/TaskController.php
> +            'actual_time' => ['nullable', 'numeric', 'regex:/^[0-9]{1,3}$|^\d{1,3}(\.\d{1,2})$/'],
[info]

整数の指定で[0-9]と\dが混在しているので統一されると良いのでは？と思いました

2022-01-22 08:07 UTC, fjsho approved these changes
佐藤さんお疲れ様です！
こちらエラーが出ないことを確認しました。
修正ありがとうございました！LGTMです！

2022-01-22 10:16 UTC, merged